[frontend_servers]
frontend1 ansible_host=10.184.0.2

[appservers]
app1 ansible_host=10.184.0.3
app2 ansible_host=10.184.0.4
app3 ansible_host=10.184.0.5

[mongodb]
mongo ansible_host=10.184.0.6


[all:vars]
ansible_user=maritzaadelia076
ansible_ssh_private_key_file=/home/maritzaadelia076/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
ansible_become=true
ansible_become_method=sudo